# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roam
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'RoamTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
